# Snippet de configuration : Interface Agrégée (LAG) et Sous-interfaces VLAN
# Équipement : Fortinet FortiGate 60F

config system interface
    
    # 1. Création de l'interface agrégée (LACP)
    edit "LACP_CORE"
        set vdom "root"
        set type aggregate
        set member "port3" "port4"
        set lacp-mode active
        set role lan
        set snmp-index 10
    next
    
    # 2. Création de la sous-interface VLAN 10 (Admin)
    edit "VLAN_10_ADMIN"
        set vdom "root"
        set ip 10.20.10.254 255.255.255.0
        set allowaccess ping https ssh
        set type vlan
        set interface "LACP_CORE"
        set vlanid 10
        set role lan
    next
    
    # 3. Création de la sous-interface VLAN 50 (PC)
    edit "VLAN_50_PC"
        set vdom "root"
        set ip 10.20.50.254 255.255.255.0
        set allowaccess ping
        set type vlan
        set interface "LACP_CORE"
        set vlanid 50
        set role lan
    next

    # 4. Création du VLAN 1000 (Transition / Merdouille)
    edit "VLAN_1000_MERD"
        set vdom "root"
        set ip 10.20.1000.254 255.255.255.0
        set allowaccess ping
        set type vlan
        set interface "LACP_CORE"
        set vlanid 1000
        set role lan
    next

end